// Code generated by go-swagger; DO NOT EDIT.

package price

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/yahfiilham/gold-store-demo/pkg/models"
)

// SavePriceHandlerFunc turns a function with the right signature into a save price handler
type SavePriceHandlerFunc func(SavePriceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SavePriceHandlerFunc) Handle(params SavePriceParams) middleware.Responder {
	return fn(params)
}

// SavePriceHandler interface for that can handle valid save price params
type SavePriceHandler interface {
	Handle(SavePriceParams) middleware.Responder
}

// NewSavePrice creates a new http.Handler for the save price operation
func NewSavePrice(ctx *middleware.Context, handler SavePriceHandler) *SavePrice {
	return &SavePrice{Context: ctx, Handler: handler}
}

/* SavePrice swagger:route POST /price price savePrice

input price

api for input price

*/
type SavePrice struct {
	Context *middleware.Context
	Handler SavePriceHandler
}

func (o *SavePrice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSavePriceParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// SavePriceCreatedBody save price created body
//
// swagger:model SavePriceCreatedBody
type SavePriceCreatedBody struct {

	// data
	Data *models.Price `json:"data,omitempty"`
}

// Validate validates this save price created body
func (o *SavePriceCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SavePriceCreatedBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("savePriceCreated" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("savePriceCreated" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this save price created body based on the context it is used
func (o *SavePriceCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SavePriceCreatedBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("savePriceCreated" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("savePriceCreated" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SavePriceCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SavePriceCreatedBody) UnmarshalBinary(b []byte) error {
	var res SavePriceCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
