// Code generated by go-swagger; DO NOT EDIT.

package buyback

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/yahfiilham/gold-store-demo/pkg/models"
)

// SaveBuybackReader is a Reader for the SaveBuyback structure.
type SaveBuybackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SaveBuybackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewSaveBuybackCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSaveBuybackDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSaveBuybackCreated creates a SaveBuybackCreated with default headers values
func NewSaveBuybackCreated() *SaveBuybackCreated {
	return &SaveBuybackCreated{}
}

/* SaveBuybackCreated describes a response with status code 201, with default header values.

success
*/
type SaveBuybackCreated struct {
	Payload *models.BaseResponse
}

// IsSuccess returns true when this save buyback created response has a 2xx status code
func (o *SaveBuybackCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this save buyback created response has a 3xx status code
func (o *SaveBuybackCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this save buyback created response has a 4xx status code
func (o *SaveBuybackCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this save buyback created response has a 5xx status code
func (o *SaveBuybackCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this save buyback created response a status code equal to that given
func (o *SaveBuybackCreated) IsCode(code int) bool {
	return code == 201
}

func (o *SaveBuybackCreated) Error() string {
	return fmt.Sprintf("[POST /buyback][%d] saveBuybackCreated  %+v", 201, o.Payload)
}

func (o *SaveBuybackCreated) String() string {
	return fmt.Sprintf("[POST /buyback][%d] saveBuybackCreated  %+v", 201, o.Payload)
}

func (o *SaveBuybackCreated) GetPayload() *models.BaseResponse {
	return o.Payload
}

func (o *SaveBuybackCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BaseResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSaveBuybackDefault creates a SaveBuybackDefault with default headers values
func NewSaveBuybackDefault(code int) *SaveBuybackDefault {
	return &SaveBuybackDefault{
		_statusCode: code,
	}
}

/* SaveBuybackDefault describes a response with status code -1, with default header values.

error
*/
type SaveBuybackDefault struct {
	_statusCode int

	Payload *models.BaseResponse
}

// Code gets the status code for the save buyback default response
func (o *SaveBuybackDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this save buyback default response has a 2xx status code
func (o *SaveBuybackDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this save buyback default response has a 3xx status code
func (o *SaveBuybackDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this save buyback default response has a 4xx status code
func (o *SaveBuybackDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this save buyback default response has a 5xx status code
func (o *SaveBuybackDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this save buyback default response a status code equal to that given
func (o *SaveBuybackDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *SaveBuybackDefault) Error() string {
	return fmt.Sprintf("[POST /buyback][%d] SaveBuyback default  %+v", o._statusCode, o.Payload)
}

func (o *SaveBuybackDefault) String() string {
	return fmt.Sprintf("[POST /buyback][%d] SaveBuyback default  %+v", o._statusCode, o.Payload)
}

func (o *SaveBuybackDefault) GetPayload() *models.BaseResponse {
	return o.Payload
}

func (o *SaveBuybackDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BaseResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
