// Code generated by go-swagger; DO NOT EDIT.

package transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetMutationParams creates a new GetMutationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMutationParams() *GetMutationParams {
	return &GetMutationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMutationParamsWithTimeout creates a new GetMutationParams object
// with the ability to set a timeout on a request.
func NewGetMutationParamsWithTimeout(timeout time.Duration) *GetMutationParams {
	return &GetMutationParams{
		timeout: timeout,
	}
}

// NewGetMutationParamsWithContext creates a new GetMutationParams object
// with the ability to set a context for a request.
func NewGetMutationParamsWithContext(ctx context.Context) *GetMutationParams {
	return &GetMutationParams{
		Context: ctx,
	}
}

// NewGetMutationParamsWithHTTPClient creates a new GetMutationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMutationParamsWithHTTPClient(client *http.Client) *GetMutationParams {
	return &GetMutationParams{
		HTTPClient: client,
	}
}

/* GetMutationParams contains all the parameters to send to the API endpoint
   for the get mutation operation.

   Typically these are written to a http.Request.
*/
type GetMutationParams struct {

	// AccountNo.
	AccountNo string

	// EndDate.
	EndDate int64

	// StartDate.
	StartDate int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get mutation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMutationParams) WithDefaults() *GetMutationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get mutation params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMutationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get mutation params
func (o *GetMutationParams) WithTimeout(timeout time.Duration) *GetMutationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get mutation params
func (o *GetMutationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get mutation params
func (o *GetMutationParams) WithContext(ctx context.Context) *GetMutationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get mutation params
func (o *GetMutationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get mutation params
func (o *GetMutationParams) WithHTTPClient(client *http.Client) *GetMutationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get mutation params
func (o *GetMutationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountNo adds the accountNo to the get mutation params
func (o *GetMutationParams) WithAccountNo(accountNo string) *GetMutationParams {
	o.SetAccountNo(accountNo)
	return o
}

// SetAccountNo adds the accountNo to the get mutation params
func (o *GetMutationParams) SetAccountNo(accountNo string) {
	o.AccountNo = accountNo
}

// WithEndDate adds the endDate to the get mutation params
func (o *GetMutationParams) WithEndDate(endDate int64) *GetMutationParams {
	o.SetEndDate(endDate)
	return o
}

// SetEndDate adds the endDate to the get mutation params
func (o *GetMutationParams) SetEndDate(endDate int64) {
	o.EndDate = endDate
}

// WithStartDate adds the startDate to the get mutation params
func (o *GetMutationParams) WithStartDate(startDate int64) *GetMutationParams {
	o.SetStartDate(startDate)
	return o
}

// SetStartDate adds the startDate to the get mutation params
func (o *GetMutationParams) SetStartDate(startDate int64) {
	o.StartDate = startDate
}

// WriteToRequest writes these params to a swagger request
func (o *GetMutationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param account_no
	qrAccountNo := o.AccountNo
	qAccountNo := qrAccountNo
	if qAccountNo != "" {

		if err := r.SetQueryParam("account_no", qAccountNo); err != nil {
			return err
		}
	}

	// query param end_date
	qrEndDate := o.EndDate
	qEndDate := swag.FormatInt64(qrEndDate)
	if qEndDate != "" {

		if err := r.SetQueryParam("end_date", qEndDate); err != nil {
			return err
		}
	}

	// query param start_date
	qrStartDate := o.StartDate
	qStartDate := swag.FormatInt64(qrStartDate)
	if qStartDate != "" {

		if err := r.SetQueryParam("start_date", qStartDate); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
