// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/yahfiilham/gold-store-demo/internal/apis/operations/balance"
	"github.com/yahfiilham/gold-store-demo/internal/apis/operations/buyback"
	"github.com/yahfiilham/gold-store-demo/internal/apis/operations/health_check"
	"github.com/yahfiilham/gold-store-demo/internal/apis/operations/price"
	"github.com/yahfiilham/gold-store-demo/internal/apis/operations/topup"
	"github.com/yahfiilham/gold-store-demo/internal/apis/operations/transaction"
)

// NewGoldStoreDemoAPI creates a new GoldStoreDemo instance
func NewGoldStoreDemoAPI(spec *loads.Document) *GoldStoreDemoAPI {
	return &GoldStoreDemoAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		BalanceGetBalanceHandler: balance.GetBalanceHandlerFunc(func(params balance.GetBalanceParams) middleware.Responder {
			return middleware.NotImplemented("operation balance.GetBalance has not yet been implemented")
		}),
		TransactionGetMutationHandler: transaction.GetMutationHandlerFunc(func(params transaction.GetMutationParams) middleware.Responder {
			return middleware.NotImplemented("operation transaction.GetMutation has not yet been implemented")
		}),
		PriceGetPriceHandler: price.GetPriceHandlerFunc(func(params price.GetPriceParams) middleware.Responder {
			return middleware.NotImplemented("operation price.GetPrice has not yet been implemented")
		}),
		BuybackSaveBuybackHandler: buyback.SaveBuybackHandlerFunc(func(params buyback.SaveBuybackParams) middleware.Responder {
			return middleware.NotImplemented("operation buyback.SaveBuyback has not yet been implemented")
		}),
		PriceSavePriceHandler: price.SavePriceHandlerFunc(func(params price.SavePriceParams) middleware.Responder {
			return middleware.NotImplemented("operation price.SavePrice has not yet been implemented")
		}),
		TopupSaveTopupGoldHandler: topup.SaveTopupGoldHandlerFunc(func(params topup.SaveTopupGoldParams) middleware.Responder {
			return middleware.NotImplemented("operation topup.SaveTopupGold has not yet been implemented")
		}),
		HealthCheckGetHealthCheckHandler: health_check.GetHealthCheckHandlerFunc(func(params health_check.GetHealthCheckParams) middleware.Responder {
			return middleware.NotImplemented("operation health_check.GetHealthCheck has not yet been implemented")
		}),
	}
}

/*GoldStoreDemoAPI This is a simple gold store API. */
type GoldStoreDemoAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// BalanceGetBalanceHandler sets the operation handler for the get balance operation
	BalanceGetBalanceHandler balance.GetBalanceHandler
	// TransactionGetMutationHandler sets the operation handler for the get mutation operation
	TransactionGetMutationHandler transaction.GetMutationHandler
	// PriceGetPriceHandler sets the operation handler for the get price operation
	PriceGetPriceHandler price.GetPriceHandler
	// BuybackSaveBuybackHandler sets the operation handler for the save buyback operation
	BuybackSaveBuybackHandler buyback.SaveBuybackHandler
	// PriceSavePriceHandler sets the operation handler for the save price operation
	PriceSavePriceHandler price.SavePriceHandler
	// TopupSaveTopupGoldHandler sets the operation handler for the save topup gold operation
	TopupSaveTopupGoldHandler topup.SaveTopupGoldHandler
	// HealthCheckGetHealthCheckHandler sets the operation handler for the get health check operation
	HealthCheckGetHealthCheckHandler health_check.GetHealthCheckHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *GoldStoreDemoAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *GoldStoreDemoAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *GoldStoreDemoAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *GoldStoreDemoAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *GoldStoreDemoAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *GoldStoreDemoAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *GoldStoreDemoAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *GoldStoreDemoAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *GoldStoreDemoAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the GoldStoreDemoAPI
func (o *GoldStoreDemoAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BalanceGetBalanceHandler == nil {
		unregistered = append(unregistered, "balance.GetBalanceHandler")
	}
	if o.TransactionGetMutationHandler == nil {
		unregistered = append(unregistered, "transaction.GetMutationHandler")
	}
	if o.PriceGetPriceHandler == nil {
		unregistered = append(unregistered, "price.GetPriceHandler")
	}
	if o.BuybackSaveBuybackHandler == nil {
		unregistered = append(unregistered, "buyback.SaveBuybackHandler")
	}
	if o.PriceSavePriceHandler == nil {
		unregistered = append(unregistered, "price.SavePriceHandler")
	}
	if o.TopupSaveTopupGoldHandler == nil {
		unregistered = append(unregistered, "topup.SaveTopupGoldHandler")
	}
	if o.HealthCheckGetHealthCheckHandler == nil {
		unregistered = append(unregistered, "health_check.GetHealthCheckHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *GoldStoreDemoAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *GoldStoreDemoAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *GoldStoreDemoAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *GoldStoreDemoAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *GoldStoreDemoAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *GoldStoreDemoAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the gold store demo API
func (o *GoldStoreDemoAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *GoldStoreDemoAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/balance"] = balance.NewGetBalance(o.context, o.BalanceGetBalanceHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/mutation"] = transaction.NewGetMutation(o.context, o.TransactionGetMutationHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/price"] = price.NewGetPrice(o.context, o.PriceGetPriceHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/buyback"] = buyback.NewSaveBuyback(o.context, o.BuybackSaveBuybackHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/price"] = price.NewSavePrice(o.context, o.PriceSavePriceHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/topup"] = topup.NewSaveTopupGold(o.context, o.TopupSaveTopupGoldHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/health"] = health_check.NewGetHealthCheck(o.context, o.HealthCheckGetHealthCheckHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *GoldStoreDemoAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *GoldStoreDemoAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *GoldStoreDemoAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *GoldStoreDemoAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *GoldStoreDemoAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
