// Code generated by go-swagger; DO NOT EDIT.

package topup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SaveTopupGoldHandlerFunc turns a function with the right signature into a save topup gold handler
type SaveTopupGoldHandlerFunc func(SaveTopupGoldParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SaveTopupGoldHandlerFunc) Handle(params SaveTopupGoldParams) middleware.Responder {
	return fn(params)
}

// SaveTopupGoldHandler interface for that can handle valid save topup gold params
type SaveTopupGoldHandler interface {
	Handle(SaveTopupGoldParams) middleware.Responder
}

// NewSaveTopupGold creates a new http.Handler for the save topup gold operation
func NewSaveTopupGold(ctx *middleware.Context, handler SaveTopupGoldHandler) *SaveTopupGold {
	return &SaveTopupGold{Context: ctx, Handler: handler}
}

/* SaveTopupGold swagger:route POST /topup topup saveTopupGold

topup

api for topup

*/
type SaveTopupGold struct {
	Context *middleware.Context
	Handler SaveTopupGoldHandler
}

func (o *SaveTopupGold) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSaveTopupGoldParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
