// Code generated by go-swagger; DO NOT EDIT.

package topup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/yahfiilham/gold-store-demo/pkg/models"
)

// NewSaveTopupGoldParams creates a new SaveTopupGoldParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSaveTopupGoldParams() *SaveTopupGoldParams {
	return &SaveTopupGoldParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSaveTopupGoldParamsWithTimeout creates a new SaveTopupGoldParams object
// with the ability to set a timeout on a request.
func NewSaveTopupGoldParamsWithTimeout(timeout time.Duration) *SaveTopupGoldParams {
	return &SaveTopupGoldParams{
		timeout: timeout,
	}
}

// NewSaveTopupGoldParamsWithContext creates a new SaveTopupGoldParams object
// with the ability to set a context for a request.
func NewSaveTopupGoldParamsWithContext(ctx context.Context) *SaveTopupGoldParams {
	return &SaveTopupGoldParams{
		Context: ctx,
	}
}

// NewSaveTopupGoldParamsWithHTTPClient creates a new SaveTopupGoldParams object
// with the ability to set a custom HTTPClient for a request.
func NewSaveTopupGoldParamsWithHTTPClient(client *http.Client) *SaveTopupGoldParams {
	return &SaveTopupGoldParams{
		HTTPClient: client,
	}
}

/* SaveTopupGoldParams contains all the parameters to send to the API endpoint
   for the save topup gold operation.

   Typically these are written to a http.Request.
*/
type SaveTopupGoldParams struct {

	// Data.
	Data *models.BaseRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the save topup gold params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SaveTopupGoldParams) WithDefaults() *SaveTopupGoldParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the save topup gold params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SaveTopupGoldParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the save topup gold params
func (o *SaveTopupGoldParams) WithTimeout(timeout time.Duration) *SaveTopupGoldParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the save topup gold params
func (o *SaveTopupGoldParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the save topup gold params
func (o *SaveTopupGoldParams) WithContext(ctx context.Context) *SaveTopupGoldParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the save topup gold params
func (o *SaveTopupGoldParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the save topup gold params
func (o *SaveTopupGoldParams) WithHTTPClient(client *http.Client) *SaveTopupGoldParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the save topup gold params
func (o *SaveTopupGoldParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the save topup gold params
func (o *SaveTopupGoldParams) WithData(data *models.BaseRequest) *SaveTopupGoldParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the save topup gold params
func (o *SaveTopupGoldParams) SetData(data *models.BaseRequest) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *SaveTopupGoldParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
