// Code generated by go-swagger; DO NOT EDIT.

package topup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/yahfiilham/gold-store-demo/pkg/models"
)

// SaveTopupGoldReader is a Reader for the SaveTopupGold structure.
type SaveTopupGoldReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SaveTopupGoldReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewSaveTopupGoldCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSaveTopupGoldDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSaveTopupGoldCreated creates a SaveTopupGoldCreated with default headers values
func NewSaveTopupGoldCreated() *SaveTopupGoldCreated {
	return &SaveTopupGoldCreated{}
}

/* SaveTopupGoldCreated describes a response with status code 201, with default header values.

success
*/
type SaveTopupGoldCreated struct {
	Payload *models.BaseResponse
}

// IsSuccess returns true when this save topup gold created response has a 2xx status code
func (o *SaveTopupGoldCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this save topup gold created response has a 3xx status code
func (o *SaveTopupGoldCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this save topup gold created response has a 4xx status code
func (o *SaveTopupGoldCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this save topup gold created response has a 5xx status code
func (o *SaveTopupGoldCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this save topup gold created response a status code equal to that given
func (o *SaveTopupGoldCreated) IsCode(code int) bool {
	return code == 201
}

func (o *SaveTopupGoldCreated) Error() string {
	return fmt.Sprintf("[POST /topup][%d] saveTopupGoldCreated  %+v", 201, o.Payload)
}

func (o *SaveTopupGoldCreated) String() string {
	return fmt.Sprintf("[POST /topup][%d] saveTopupGoldCreated  %+v", 201, o.Payload)
}

func (o *SaveTopupGoldCreated) GetPayload() *models.BaseResponse {
	return o.Payload
}

func (o *SaveTopupGoldCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BaseResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSaveTopupGoldDefault creates a SaveTopupGoldDefault with default headers values
func NewSaveTopupGoldDefault(code int) *SaveTopupGoldDefault {
	return &SaveTopupGoldDefault{
		_statusCode: code,
	}
}

/* SaveTopupGoldDefault describes a response with status code -1, with default header values.

error
*/
type SaveTopupGoldDefault struct {
	_statusCode int

	Payload *models.BaseResponse
}

// Code gets the status code for the save topup gold default response
func (o *SaveTopupGoldDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this save topup gold default response has a 2xx status code
func (o *SaveTopupGoldDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this save topup gold default response has a 3xx status code
func (o *SaveTopupGoldDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this save topup gold default response has a 4xx status code
func (o *SaveTopupGoldDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this save topup gold default response has a 5xx status code
func (o *SaveTopupGoldDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this save topup gold default response a status code equal to that given
func (o *SaveTopupGoldDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *SaveTopupGoldDefault) Error() string {
	return fmt.Sprintf("[POST /topup][%d] SaveTopupGold default  %+v", o._statusCode, o.Payload)
}

func (o *SaveTopupGoldDefault) String() string {
	return fmt.Sprintf("[POST /topup][%d] SaveTopupGold default  %+v", o._statusCode, o.Payload)
}

func (o *SaveTopupGoldDefault) GetPayload() *models.BaseResponse {
	return o.Payload
}

func (o *SaveTopupGoldDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BaseResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
