// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AccountData account data
//
// swagger:model accountData
type AccountData struct {

	// account number
	AccountNumber string `json:"accountNumber,omitempty"`

	// balance
	Balance float64 `json:"balance,omitempty" gorm:"type:decimal(10,3)"`
}

// Validate validates this account data
func (m *AccountData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this account data based on context it is used
func (m *AccountData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AccountData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountData) UnmarshalBinary(b []byte) error {
	var res AccountData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
