// Code generated by go-swagger; DO NOT EDIT.

package price

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new price API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for price API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetPrice(params *GetPriceParams, opts ...ClientOption) (*GetPriceOK, error)

	SavePrice(params *SavePriceParams, opts ...ClientOption) (*SavePriceCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetPrice gets price

  api for get current price
*/
func (a *Client) GetPrice(params *GetPriceParams, opts ...ClientOption) (*GetPriceOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetPriceParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetPrice",
		Method:             "GET",
		PathPattern:        "/price",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetPriceReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetPriceOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetPriceDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  SavePrice inputs price

  api for input price
*/
func (a *Client) SavePrice(params *SavePriceParams, opts ...ClientOption) (*SavePriceCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSavePriceParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "SavePrice",
		Method:             "POST",
		PathPattern:        "/price",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &SavePriceReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SavePriceCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*SavePriceDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
