// Code generated by go-swagger; DO NOT EDIT.

package price

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/yahfiilham/gold-store-demo/pkg/models"
)

// SavePriceReader is a Reader for the SavePrice structure.
type SavePriceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SavePriceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewSavePriceCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSavePriceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSavePriceCreated creates a SavePriceCreated with default headers values
func NewSavePriceCreated() *SavePriceCreated {
	return &SavePriceCreated{}
}

/* SavePriceCreated describes a response with status code 201, with default header values.

success
*/
type SavePriceCreated struct {
	Payload *SavePriceCreatedBody
}

// IsSuccess returns true when this save price created response has a 2xx status code
func (o *SavePriceCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this save price created response has a 3xx status code
func (o *SavePriceCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this save price created response has a 4xx status code
func (o *SavePriceCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this save price created response has a 5xx status code
func (o *SavePriceCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this save price created response a status code equal to that given
func (o *SavePriceCreated) IsCode(code int) bool {
	return code == 201
}

func (o *SavePriceCreated) Error() string {
	return fmt.Sprintf("[POST /price][%d] savePriceCreated  %+v", 201, o.Payload)
}

func (o *SavePriceCreated) String() string {
	return fmt.Sprintf("[POST /price][%d] savePriceCreated  %+v", 201, o.Payload)
}

func (o *SavePriceCreated) GetPayload() *SavePriceCreatedBody {
	return o.Payload
}

func (o *SavePriceCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SavePriceCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSavePriceDefault creates a SavePriceDefault with default headers values
func NewSavePriceDefault(code int) *SavePriceDefault {
	return &SavePriceDefault{
		_statusCode: code,
	}
}

/* SavePriceDefault describes a response with status code -1, with default header values.

error
*/
type SavePriceDefault struct {
	_statusCode int

	Payload *models.BaseResponse
}

// Code gets the status code for the save price default response
func (o *SavePriceDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this save price default response has a 2xx status code
func (o *SavePriceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this save price default response has a 3xx status code
func (o *SavePriceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this save price default response has a 4xx status code
func (o *SavePriceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this save price default response has a 5xx status code
func (o *SavePriceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this save price default response a status code equal to that given
func (o *SavePriceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *SavePriceDefault) Error() string {
	return fmt.Sprintf("[POST /price][%d] SavePrice default  %+v", o._statusCode, o.Payload)
}

func (o *SavePriceDefault) String() string {
	return fmt.Sprintf("[POST /price][%d] SavePrice default  %+v", o._statusCode, o.Payload)
}

func (o *SavePriceDefault) GetPayload() *models.BaseResponse {
	return o.Payload
}

func (o *SavePriceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BaseResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SavePriceCreatedBody save price created body
swagger:model SavePriceCreatedBody
*/
type SavePriceCreatedBody struct {

	// data
	Data *models.Price `json:"data,omitempty"`
}

// Validate validates this save price created body
func (o *SavePriceCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SavePriceCreatedBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("savePriceCreated" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("savePriceCreated" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this save price created body based on the context it is used
func (o *SavePriceCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SavePriceCreatedBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("savePriceCreated" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("savePriceCreated" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SavePriceCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SavePriceCreatedBody) UnmarshalBinary(b []byte) error {
	var res SavePriceCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
