// Code generated by go-swagger; DO NOT EDIT.

package price

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/yahfiilham/gold-store-demo/pkg/models"
)

// NewSavePriceParams creates a new SavePriceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSavePriceParams() *SavePriceParams {
	return &SavePriceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSavePriceParamsWithTimeout creates a new SavePriceParams object
// with the ability to set a timeout on a request.
func NewSavePriceParamsWithTimeout(timeout time.Duration) *SavePriceParams {
	return &SavePriceParams{
		timeout: timeout,
	}
}

// NewSavePriceParamsWithContext creates a new SavePriceParams object
// with the ability to set a context for a request.
func NewSavePriceParamsWithContext(ctx context.Context) *SavePriceParams {
	return &SavePriceParams{
		Context: ctx,
	}
}

// NewSavePriceParamsWithHTTPClient creates a new SavePriceParams object
// with the ability to set a custom HTTPClient for a request.
func NewSavePriceParamsWithHTTPClient(client *http.Client) *SavePriceParams {
	return &SavePriceParams{
		HTTPClient: client,
	}
}

/* SavePriceParams contains all the parameters to send to the API endpoint
   for the save price operation.

   Typically these are written to a http.Request.
*/
type SavePriceParams struct {

	// Data.
	Data *models.PriceData

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the save price params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SavePriceParams) WithDefaults() *SavePriceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the save price params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SavePriceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the save price params
func (o *SavePriceParams) WithTimeout(timeout time.Duration) *SavePriceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the save price params
func (o *SavePriceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the save price params
func (o *SavePriceParams) WithContext(ctx context.Context) *SavePriceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the save price params
func (o *SavePriceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the save price params
func (o *SavePriceParams) WithHTTPClient(client *http.Client) *SavePriceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the save price params
func (o *SavePriceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the save price params
func (o *SavePriceParams) WithData(data *models.PriceData) *SavePriceParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the save price params
func (o *SavePriceParams) SetData(data *models.PriceData) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *SavePriceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
