// Code generated by go-swagger; DO NOT EDIT.

// Package apis Gold Store Demo
//
//  This is a simple gold store API.
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /
//  Version: 1.0.0
//  License: Apache 2.0 https://www.apache.org/licenses/LICENSE-2.0
//  Contact: gold store maintainers<gold.store@email.com> http://localhost:8081/docs
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package apis
