// Code generated by go-swagger; DO NOT EDIT.

package apis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a simple gold store API.",
    "title": "Gold Store Demo",
    "contact": {
      "name": "gold store maintainers",
      "url": "http://localhost:8081/docs",
      "email": "gold.store@email.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    },
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "paths": {
    "/health": {
      "get": {
        "tags": [
          "health check"
        ],
        "summary": "check server",
        "operationId": "getHealthCheck",
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "$ref": "#/definitions/baseResponse"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/baseResponse"
            }
          }
        }
      }
    },
    "/price": {
      "get": {
        "description": "api for get current price",
        "tags": [
          "price"
        ],
        "summary": "get price",
        "operationId": "GetPrice",
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "type": "object",
              "properties": {
                "data": {
                  "$ref": "#/definitions/price"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/baseResponse"
            }
          }
        }
      },
      "post": {
        "description": "api for input price",
        "tags": [
          "price"
        ],
        "summary": "input price",
        "operationId": "SavePrice",
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/priceData"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "success",
            "schema": {
              "type": "object",
              "properties": {
                "data": {
                  "$ref": "#/definitions/price"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/baseResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "baseResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "modelID": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "x-go-custom-tag": "gorm:\"type:int primary key auto_increment\""
        }
      }
    },
    "modelLogTime": {
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "integer",
          "format": "date-time",
          "x-go-custom-tag": "gorm:\"type:int;autoCreateTime\""
        },
        "updatedAt": {
          "type": "integer",
          "format": "date-time",
          "x-go-custom-tag": "gorm:\"type:int;autoUpdateTime\""
        }
      }
    },
    "price": {
      "allOf": [
        {
          "$ref": "#/definitions/modelID"
        },
        {
          "$ref": "#/definitions/modelLogTime"
        },
        {
          "$ref": "#/definitions/priceData"
        }
      ]
    },
    "priceData": {
      "type": "object",
      "properties": {
        "buybackPrice": {
          "type": "number",
          "format": "double"
        },
        "topupPrice": {
          "type": "number",
          "format": "double"
        }
      }
    }
  },
  "responses": {
    "badRequest": {
      "description": "something wrong when send request to server",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    },
    "created": {
      "description": "the request to the server was successful",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    },
    "forbiddenAccess": {
      "description": "the client don` + "`" + `t have access to the resource",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    },
    "internalServerError": {
      "description": "Internal Server Error",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    },
    "notFound": {
      "description": "the request resource is not found",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    },
    "success": {
      "description": "the request to the server was successful",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    },
    "unauthorized": {
      "description": "the client must be authenticated to perform this request",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    },
    "unprocessableEntity": {
      "description": "The request is correct but server can` + "`" + `t process the request",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a simple gold store API.",
    "title": "Gold Store Demo",
    "contact": {
      "name": "gold store maintainers",
      "url": "http://localhost:8081/docs",
      "email": "gold.store@email.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    },
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "paths": {
    "/health": {
      "get": {
        "tags": [
          "health check"
        ],
        "summary": "check server",
        "operationId": "getHealthCheck",
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "$ref": "#/definitions/baseResponse"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/baseResponse"
            }
          }
        }
      }
    },
    "/price": {
      "get": {
        "description": "api for get current price",
        "tags": [
          "price"
        ],
        "summary": "get price",
        "operationId": "GetPrice",
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "type": "object",
              "properties": {
                "data": {
                  "$ref": "#/definitions/price"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/baseResponse"
            }
          }
        }
      },
      "post": {
        "description": "api for input price",
        "tags": [
          "price"
        ],
        "summary": "input price",
        "operationId": "SavePrice",
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/priceData"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "success",
            "schema": {
              "type": "object",
              "properties": {
                "data": {
                  "$ref": "#/definitions/price"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/baseResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "baseResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "modelID": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "x-go-custom-tag": "gorm:\"type:int primary key auto_increment\""
        }
      }
    },
    "modelLogTime": {
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "integer",
          "format": "date-time",
          "x-go-custom-tag": "gorm:\"type:int;autoCreateTime\""
        },
        "updatedAt": {
          "type": "integer",
          "format": "date-time",
          "x-go-custom-tag": "gorm:\"type:int;autoUpdateTime\""
        }
      }
    },
    "price": {
      "allOf": [
        {
          "$ref": "#/definitions/modelID"
        },
        {
          "$ref": "#/definitions/modelLogTime"
        },
        {
          "$ref": "#/definitions/priceData"
        }
      ]
    },
    "priceData": {
      "type": "object",
      "properties": {
        "buybackPrice": {
          "type": "number",
          "format": "double"
        },
        "topupPrice": {
          "type": "number",
          "format": "double"
        }
      }
    }
  },
  "responses": {
    "badRequest": {
      "description": "something wrong when send request to server",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    },
    "created": {
      "description": "the request to the server was successful",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    },
    "forbiddenAccess": {
      "description": "the client don` + "`" + `t have access to the resource",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    },
    "internalServerError": {
      "description": "Internal Server Error",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    },
    "notFound": {
      "description": "the request resource is not found",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    },
    "success": {
      "description": "the request to the server was successful",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    },
    "unauthorized": {
      "description": "the client must be authenticated to perform this request",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    },
    "unprocessableEntity": {
      "description": "The request is correct but server can` + "`" + `t process the request",
      "schema": {
        "$ref": "#/definitions/baseResponse"
      }
    }
  }
}`))
}
