// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/yahfiilham/gold-store-demo/pkg/client/balance"
	"github.com/yahfiilham/gold-store-demo/pkg/client/buyback"
	"github.com/yahfiilham/gold-store-demo/pkg/client/health_check"
	"github.com/yahfiilham/gold-store-demo/pkg/client/price"
	"github.com/yahfiilham/gold-store-demo/pkg/client/topup"
	"github.com/yahfiilham/gold-store-demo/pkg/client/transaction"
)

// Default gold store demo HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost:8080"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new gold store demo HTTP client.
func NewHTTPClient(formats strfmt.Registry) *GoldStoreDemo {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new gold store demo HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *GoldStoreDemo {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new gold store demo client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *GoldStoreDemo {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(GoldStoreDemo)
	cli.Transport = transport
	cli.Balance = balance.New(transport, formats)
	cli.Buyback = buyback.New(transport, formats)
	cli.HealthCheck = health_check.New(transport, formats)
	cli.Price = price.New(transport, formats)
	cli.Topup = topup.New(transport, formats)
	cli.Transaction = transaction.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// GoldStoreDemo is a client for gold store demo
type GoldStoreDemo struct {
	Balance balance.ClientService

	Buyback buyback.ClientService

	HealthCheck health_check.ClientService

	Price price.ClientService

	Topup topup.ClientService

	Transaction transaction.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *GoldStoreDemo) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Balance.SetTransport(transport)
	c.Buyback.SetTransport(transport)
	c.HealthCheck.SetTransport(transport)
	c.Price.SetTransport(transport)
	c.Topup.SetTransport(transport)
	c.Transaction.SetTransport(transport)
}
