// Code generated by go-swagger; DO NOT EDIT.

package balance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetBalanceParams creates a new GetBalanceParams object
//
// There are no default values defined in the spec.
func NewGetBalanceParams() GetBalanceParams {

	return GetBalanceParams{}
}

// GetBalanceParams contains all the bound params for the get balance operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetBalance
type GetBalanceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	AccountNo string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetBalanceParams() beforehand.
func (o *GetBalanceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qAccountNo, qhkAccountNo, _ := qs.GetOK("account_no")
	if err := o.bindAccountNo(qAccountNo, qhkAccountNo, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAccountNo binds and validates parameter AccountNo from query.
func (o *GetBalanceParams) bindAccountNo(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("account_no", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("account_no", "query", raw); err != nil {
		return err
	}
	o.AccountNo = raw

	return nil
}
