// Code generated by go-swagger; DO NOT EDIT.

package balance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/yahfiilham/gold-store-demo/pkg/models"
)

// GetBalanceHandlerFunc turns a function with the right signature into a get balance handler
type GetBalanceHandlerFunc func(GetBalanceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBalanceHandlerFunc) Handle(params GetBalanceParams) middleware.Responder {
	return fn(params)
}

// GetBalanceHandler interface for that can handle valid get balance params
type GetBalanceHandler interface {
	Handle(GetBalanceParams) middleware.Responder
}

// NewGetBalance creates a new http.Handler for the get balance operation
func NewGetBalance(ctx *middleware.Context, handler GetBalanceHandler) *GetBalance {
	return &GetBalance{Context: ctx, Handler: handler}
}

/* GetBalance swagger:route GET /balance balance getBalance

get balance

api for get balance

*/
type GetBalance struct {
	Context *middleware.Context
	Handler GetBalanceHandler
}

func (o *GetBalance) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBalanceParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetBalanceOKBody get balance o k body
//
// swagger:model GetBalanceOKBody
type GetBalanceOKBody struct {

	// data
	Data *models.Account `json:"data,omitempty"`
}

// Validate validates this get balance o k body
func (o *GetBalanceOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetBalanceOKBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getBalanceOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getBalanceOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get balance o k body based on the context it is used
func (o *GetBalanceOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetBalanceOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {
		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getBalanceOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getBalanceOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetBalanceOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetBalanceOKBody) UnmarshalBinary(b []byte) error {
	var res GetBalanceOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
