// Code generated by go-swagger; DO NOT EDIT.

package buyback

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/yahfiilham/gold-store-demo/pkg/models"
)

// SaveBuybackCreatedCode is the HTTP code returned for type SaveBuybackCreated
const SaveBuybackCreatedCode int = 201

/*SaveBuybackCreated success

swagger:response saveBuybackCreated
*/
type SaveBuybackCreated struct {

	/*
	  In: Body
	*/
	Payload *models.BaseResponse `json:"body,omitempty"`
}

// NewSaveBuybackCreated creates SaveBuybackCreated with default headers values
func NewSaveBuybackCreated() *SaveBuybackCreated {

	return &SaveBuybackCreated{}
}

// WithPayload adds the payload to the save buyback created response
func (o *SaveBuybackCreated) WithPayload(payload *models.BaseResponse) *SaveBuybackCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the save buyback created response
func (o *SaveBuybackCreated) SetPayload(payload *models.BaseResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SaveBuybackCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SaveBuybackDefault error

swagger:response saveBuybackDefault
*/
type SaveBuybackDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.BaseResponse `json:"body,omitempty"`
}

// NewSaveBuybackDefault creates SaveBuybackDefault with default headers values
func NewSaveBuybackDefault(code int) *SaveBuybackDefault {
	if code <= 0 {
		code = 500
	}

	return &SaveBuybackDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the save buyback default response
func (o *SaveBuybackDefault) WithStatusCode(code int) *SaveBuybackDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the save buyback default response
func (o *SaveBuybackDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the save buyback default response
func (o *SaveBuybackDefault) WithPayload(payload *models.BaseResponse) *SaveBuybackDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the save buyback default response
func (o *SaveBuybackDefault) SetPayload(payload *models.BaseResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SaveBuybackDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
